name: Vending Machine

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_WORKSPACE: ${{ github.event.inputs.env }}

      TF_VAR_tenant_id: ${{ vars.TENANT_ID }}
      TF_VAR_subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      TF_VAR_resource_group_name: ${{ vars.RESOURCE_GROUP_NAME }}
      TF_VAR_location: ${{ vars.LOCATION }}
      TF_VAR_amiasea_db_admins_group_id: ${{ vars.AMIASEA_DB_ADMINS_GROUP_ID }}
      TF_VAR_ghcr_pat_versionless_id: ${{ vars.GHCR_PAT_VERSIONLESS_ID }}
      TF_VAR_env: "dev"

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Fetch TF Token
        id: fetch-token
        run: |
          # Use Azure CLI to pull the token
          RAW_TOKEN=$(az keyvault secret show \
            --id "${{ vars.TF_TOKEN_VERSIONLESS_ID }}" \
            --query value -o tsv)
          
          # MASK IT: Immediately prevents the token from appearing in logs
          echo "::add-mask::$RAW_TOKEN"
          
          # INJECT: Set the dynamic env var for subsequent steps
          echo "TF_TOKEN_app_terraform_io=$RAW_TOKEN" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.6"
          terraform_wrapper: false

      - name: Vending Machine
        working-directory: ./terraform/2_vending_machine
        run: |
          terraform init
          terraform apply -auto-approve